# Generated by Django 5.2.17 on 2026-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='goal_coins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='goal_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='goal_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='pledged_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='speaker_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
