# Generated by Django 5.2.17 on 2026-08-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_initial'),
        ('rooms', '0004_room_goal_coins_room_goal_reached_at_room_goal_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('escrowed', 'Escrowed'), ('settled', 'Settled'), ('refunded', 'Refunded')], db_index=True, default='escrowed', max_length=10)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('coins', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-coins', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(choices=[('topup', 'Topup'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('question_escrow', 'Question Escrow'), ('question_paid', 'Question Paid'), ('question_refund', 'Question Refund'), ('pledge_escrow', 'Pledge Escrow'), ('pledge_settled', 'Pledge Settled'), ('pledge_refund', 'Pledge Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('label',), name='unique_system_wallet'),
        ),
        migrations.AddField(
            model_name='goalpledge',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='goalpledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='economy.goalpledge'),
        ),
        migrations.AddField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='economy.question'),
        ),
        migrations.AddIndex(
            model_name='goalpledge',
            index=models.Index(fields=['room', 'status'], name='economy_goa_room_id_12085a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['room', 'status', '-coins'], name='economy_que_room_id_5df043_idx'),
        ),
    ]
